name: CMake

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: nuspell/nuspell
          ref: v5.0.0

      - name: Dependency
        run: |
          vcpkg install icu

      - name: Build
        run: |
          echo sed -i "/set_target_properties(nuspell-bin PROPERTIES/a\`n    LINK_FLAGS `"/SUBSYSTEM:CONSOLE`"" src/nuspell/CMakeLists.txt
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake -A Win32
          echo cmake --build . --config Release
          cmake --build .
          cmake --install . --prefix c:\nuspell
          echo cp src\tools\Release\icu*.dll c:\nuspell\bin
          cp src\tools\Debug\icu*.dll c:\nuspell\bin

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
