name: CMake

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: nuspell/nuspell
          ref: v5.0.0

      - name: Dependency
        run: |
          vcpkg install icu

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake -A Win32
          cmake --build .
